version: "3.3"
services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
  frontend:
    build: ./frontend
  user:
    build: ./user
    ports:
      - "7712:7712"
    environment:
      - PROJECT_ID=my-project
      - INSTANCE_ID=my-instance
      - TABLE_NAME=vaccine-reservation-system
      - SECRET=my-secret
      - SPEC_ENABLED=true
      - SPEC_FILES=./docs/swagger-ui
      - ACCESS_LOG=true
      - BIGTABLE_EMULATOR_HOST=bigtable:8086
  reservation:
    build: ./reservation
    ports:
      - "7713:7712"
    environment:
      - PROJECT_ID=my-project
      - INSTANCE_ID=my-instance
      - TABLE_NAME=vaccine-reservation-system
      - SECRET=my-secret
      - SPEC_ENABLED=true
      - SPEC_FILES=./docs/swagger-ui
      - ACCESS_LOG=true
      - BIGTABLE_EMULATOR_HOST=bigtable:8086
  hospital:
    build: ./hospital
    ports:
      - "7714:7712"
    environment:
      - PROJECT_ID=my-project
      - INSTANCE_ID=my-instance
      - TABLE_NAME=vaccine-reservation-system
      - SPEC_ENABLED=true
      - SPEC_FILES=./docs/swagger-ui
      - ACCESS_LOG=true
      - BIGTABLE_EMULATOR_HOST=bigtable:8086
  bigtable:
    image: google/cloud-sdk:latest
    ports:
      - "127.0.0.1:8086:8086"
    command:
      - "/bin/bash"
      - "-c"
      - "gcloud beta emulators bigtable start --host-port=0.0.0.0:8086"
