basePath: /
consumes:
- application/json
definitions:
  APIError:
    properties:
      error:
        description: |-
          The status error message.
          in: body
        type: string
        x-go-name: ErrMsg
      message:
        description: |-
          The error message.
          in: body
        type: string
        x-go-name: Message
      status:
        description: |-
          The HTTP status code.
          in: body
        format: int64
        type: integer
        x-go-name: Status
      timestamp:
        description: |-
          The timestamp of the error.
          in: body
        type: string
        x-go-name: Timestamp
    required:
    - timestamp
    - status
    - error
    - message
    title: APIError is the error response for the API.
    type: object
    x-go-package: github.com/MortalHappiness/VaccineReservationSystem/go-utils/apierrors
  HospitalModel:
    description: Hospital model is the body format of HospitalResponse
    properties:
      address:
        description: The hospital address
        example: No.1, Sec. 4, Roosevelt Road, Taipei, 10617 Taiwan
        type: string
        x-go-name: Address
      county:
        description: The hospital County
        example: New Taipei City
        type: string
        x-go-name: County
      id:
        description: The hospital id
        example: "0001"
        type: string
        x-go-name: ID
      name:
        description: The hospital name
        example: Taipei City Hospital Heping Fuyou Branch
        type: string
        x-go-name: Name
      township:
        description: The hospital Township
        example: Banqiao
        type: string
        x-go-name: Township
      vaccineCnt:
        additionalProperties:
          format: int64
          type: integer
        description: The hospital vaccines
        example:
          AZ: 100
          BNT: 200
        type: object
        x-go-name: VaccineCnt
    required:
    - id
    - name
    - county
    - township
    - address
    - vaccineCnt
    type: object
    x-go-package: github.com/MortalHappiness/VaccineReservationSystem/go-utils/models
host: localhost:7712
info:
  description: Documentation of Worker.
  title: Worker.
  version: '%VERSION_TO_BE_REPLACED_BY_GITRUNNER%'
paths:
  /.spec:
    get:
      description: GetSpec returns API Spec. This API is for testing & development
        only.
      operationId: GetSpec
      responses:
        "301":
          $ref: '#/responses/emptyResponse'
        "404":
          $ref: '#/responses/genericError'
      summary: Get Server API Specification
      tags:
      - Development
  /api/hospitals:
    get:
      operationId: GetHospital
      parameters:
      - description: the county of the hospital
        in: query
        name: county
        required: true
        type: string
      - description: the township of the hospital
        in: query
        name: township
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/GetHospitalResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "404":
          $ref: '#/responses/NotFoundErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Get the hospital information.
      tags:
      - Hospital
    post:
      operationId: PostHospitalRequest
      parameters:
      - description: The hospital info
        in: body
        name: hospital
        schema:
          $ref: '#/definitions/HospitalModel'
        x-go-name: Hospital
      responses:
        "200":
          $ref: '#/responses/HospitalResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Add a new hospital.
      tags:
      - Hospital
  /api/hospitals/:hospitalID:
    delete:
      operationId: DeleteHospital
      parameters:
      - description: the county of the hospital
        in: query
        name: county
        required: true
        type: string
      - description: the township of the hospital
        in: query
        name: township
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/DeleteHospital'
          description: hospitalID
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Delete the hospital by id.
      tags:
      - Hospital
    get:
      operationId: GetHospitalByID
      parameters:
      - description: the county of the hospital
        in: query
        name: county
        required: true
        type: string
      - description: the township of the hospital
        in: query
        name: township
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/HospitalResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "404":
          $ref: '#/responses/NotFoundErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Get the hospital information by id.
      tags:
      - Hospital
    put:
      operationId: PutHospitalRequest
      parameters:
      - description: The hospital info
        in: body
        name: hospital
        schema:
          $ref: '#/definitions/HospitalModel'
        x-go-name: Hospital
      - description: the county of the hospital
        in: query
        name: county
        required: true
        type: string
      - description: the township of the hospital
        in: query
        name: township
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/HospitalResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Update a hospital.
      tags:
      - Hospital
produces:
- application/json
responses:
  BadRequestErrorResponse:
    description: BadRequestErrorResponse is the response of bad request error.
    schema:
      $ref: '#/definitions/APIError'
  GetHospitalResponse:
    description: GetHospitalResponse is the response of GetHospital
    schema:
      items:
        $ref: '#/definitions/HospitalModel'
      type: array
  HospitalResponse:
    description: HospitalResponse is the response of GetHospital
    schema:
      $ref: '#/definitions/HospitalModel'
  InternalServerErrorResponse:
    description: InternalServerErrorResponse is the response of internal server error.
    schema:
      $ref: '#/definitions/APIError'
  NotFoundErrorResponse:
    description: NotFoundErrorResponse is the response of not found error.
    schema:
      $ref: '#/definitions/APIError'
  UnauthorizedErrorResponse:
    description: UnauthorizedErrorResponse is the response of unauthorized error.
    schema:
      $ref: '#/definitions/APIError'
  emptyResponse:
    description: EmptyResponse are sent when the HTTP status code is 204.
  genericError:
    description: |-
      A GenericError is the default error message that is generated.
      For certain status codes there are more appropriate error structures.
    headers:
      message:
        description: |-
          The error message

          required: true
        type: string
schemes:
- http
swagger: "2.0"
