apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  ports:
  - port: 7712
    targetPort: 7712
    protocol: TCP
    name: http
  selector:
    app: reservation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: {{ .Values.reservation.replicas }}
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reservation
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
        - image: {{ .Values.repository }}/reservation
          name: reservation
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: PROJECT_ID
              value: "{{ .Values.project_id }}"
            - name: INSTANCE_ID
              value: "{{ .Values.instance_id }}"
            - name: TABLE_NAME
              value: "{{ .Values.table_name }}"
            - name: SECRET
              value: "my-secret"
            - name: SPEC_ENABLED
              value: "true"
            - name: SPEC_FILES
              value: "./docs/swagger-ui"
            - name: ACCESS_LOG
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json
      volumes:
        - name: google-cloud-key
          secret:
            secretName: app-key
