basePath: /
consumes:
- application/json
definitions:
  APIError:
    properties:
      error:
        description: |-
          The status error message.
          in: body
        type: string
        x-go-name: ErrMsg
      message:
        description: |-
          The error message.
          in: body
        type: string
        x-go-name: Message
      status:
        description: |-
          The HTTP status code.
          in: body
        format: int64
        type: integer
        x-go-name: Status
      timestamp:
        description: |-
          The timestamp of the error.
          in: body
        type: string
        x-go-name: Timestamp
    required:
    - timestamp
    - status
    - error
    - message
    title: APIError is the error response for the API.
    type: object
    x-go-package: github.com/MortalHappiness/VaccineReservationSystem/user/internal/apierrors
  PostSessionRequestModel:
    properties:
      healthCardID:
        description: The user's healthCardID
        example: "000011112222"
        type: string
        x-go-name: HealthCardID
      nationID:
        description: The user's nationID
        example: A123456789
        type: string
        x-go-name: NationID
    required:
    - nationID
    - healthCardID
    title: PostSessionRequestModel is the body format of PostSessionRequest.
    type: object
    x-go-package: github.com/MortalHappiness/VaccineReservationSystem/user/internal/controllers/session
  UserModel:
    description: UserModel is the body format of UserResponse
    properties:
      address:
        description: The user address
        example: No.1, Sec. 4, Roosevelt Road, Taipei, 10617 Taiwan
        type: string
        x-go-name: Address
      birthDay:
        description: The user birthday
        example: 2022/05/23
        type: string
        x-go-name: BirthDay
      gender:
        description: The user gender
        example: male
        type: string
        x-go-name: Gender
      healthCardID:
        description: The user healthCardID
        example: "000011112222"
        type: string
        x-go-name: HealthCardID
      name:
        description: The user name
        example: bob
        type: string
        x-go-name: Name
      nationID:
        description: The user nation ID
        example: A123456789
        type: string
        x-go-name: NationID
      phone:
        description: The user phone number
        example: "0912345678"
        type: string
        x-go-name: Phone
      vaccines:
        description: The user inoculated vaccines
        example: '[AZ, BNT]'
        items:
          type: string
        type: array
        x-go-name: Vaccines
    required:
    - nationID
    - healthCardID
    type: object
    x-go-package: github.com/MortalHappiness/VaccineReservationSystem/user/internal/controllers/user
host: localhost:7712
info:
  description: Documentation of Worker.
  title: Worker.
  version: '%VERSION_TO_BE_REPLACED_BY_GITRUNNER%'
paths:
  /.spec:
    get:
      description: GetSpec returns API Spec. This API is for testing & development
        only.
      operationId: GetSpec
      responses:
        "301":
          $ref: '#/responses/emptyResponse'
        "404":
          $ref: '#/responses/genericError'
      summary: Get Server API Specification
      tags:
      - Development
  /api/session:
    delete:
      operationId: DelSession
      responses:
        "204":
          $ref: '#/responses/NoContentResponse'
      summary: Logout the user.
      tags:
      - Session
    get:
      operationId: GetSession
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "401":
          $ref: '#/responses/UnauthorizedErrorResponse'
        "404":
          $ref: '#/responses/NotFoundErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Get the user information.
      tags:
      - Session
  /api/sessions:
    post:
      operationId: PostSessionRequest
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/PostSessionRequestModel'
        x-go-name: Body
      responses:
        "200":
          $ref: '#/responses/SessionResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Login.
      tags:
      - Session
  /api/users:
    post:
      operationId: PostUserRequest
      parameters:
      - description: The user info
        in: body
        name: user
        schema:
          $ref: '#/definitions/UserModel'
        x-go-name: User
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Add a new user.
      tags:
      - User
  /api/users/:nationID:
    delete:
      operationId: DelUserRequest
      parameters:
      - description: The user info
        example: '"A123456789"'
        in: body
        name: nationID
        schema:
          type: string
        x-go-name: NationID
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Delete a user with his/her nation ID.
      tags:
      - User
    get:
      operationId: GetUser
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "401":
          $ref: '#/responses/UnauthorizedErrorResponse'
        "404":
          $ref: '#/responses/NotFoundErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Get the user information.
      tags:
      - User
    put:
      operationId: PutUserRequest
      parameters:
      - description: The user info
        in: body
        name: user
        schema:
          $ref: '#/definitions/UserModel'
        x-go-name: User
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/BadRequestErrorResponse'
        "401":
          $ref: '#/responses/UnauthorizedErrorResponse'
        "500":
          $ref: '#/responses/InternalServerErrorResponse'
      summary: Update a user.
      tags:
      - User
produces:
- application/json
responses:
  BadRequestErrorResponse:
    description: BadRequestErrorResponse is the response of bad request error.
    schema:
      $ref: '#/definitions/APIError'
  InternalServerErrorResponse:
    description: InternalServerErrorResponse is the response of internal server error.
    schema:
      $ref: '#/definitions/APIError'
  NotFoundErrorResponse:
    description: NotFoundErrorResponse is the response of not found error.
    schema:
      $ref: '#/definitions/APIError'
  UnauthorizedErrorResponse:
    description: UnauthorizedErrorResponse is the response of unauthorized error.
    schema:
      $ref: '#/definitions/APIError'
  UserResponse:
    description: UserResponse is the response of GetUser/PostUser/PutUser.
    schema:
      $ref: '#/definitions/UserModel'
  emptyResponse:
    description: EmptyResponse are sent when the HTTP status code is 204.
  genericError:
    description: |-
      A GenericError is the default error message that is generated.
      For certain status codes there are more appropriate error structures.
    headers:
      message:
        description: |-
          The error message

          required: true
        type: string
schemes:
- http
swagger: "2.0"
