name: setup bigtable

on: push

jobs:
  bigtable:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang 1.17.2
      uses: actions/setup-go@v2
      with:
        go-version: "1.17.2"
    - name: echo path
      run: echo github.com/${GITHUB_REPOSITORY}/bigtable
    # - name: Install golang packages
    #   working-directory: github.com/${GITHUB_REPOSITORY}/bigtable
    #   run: go mod tidy